Add sphinx.ext.autodoc for doc build
After switching packaging to use build_sphinx, we need to add this
extension to avoid errors like:

 ERROR: Unknown directive type "automodule".

during doc build.

Change-Id: Ia9997b466d31a9422de64549a14196af173b1f63