Update puppet error messages for puppet 3.0.x
In 2.x what used to be
err: /File[/tmssp/asda]/ensure: change from absent to present failed: Could not set ...

In 3.0.x is now changed
Error: Could not set 'present' on ensure: No such file or directory - ...

Change-Id: I3e739195f63d9997214e8b706f575d54b7ec0c5b