Fix --version switch error
When you use the --version switch you get this error:
UnboundLocalError: local variable 'options' referenced before assignment

Change-Id: I84fadc601c0b53e68b57a94d07fc735a04b33a96
(cherry picked from commit 6f41529b222ad36222ceaf19ff667ae40447df84)